extends:
  - stylelint-config-standard
  - stylelint-config-rational-order
  - stylelint-config-recommended-scss
  - stylelint-prettier/recommended

plugins:
  - stylelint-order

rules:
  length-zero-no-unit: null
  declaration-empty-line-before: null
  order/properties-order: []
  plugin/rational-order:
    - true
    - empty-line-between-groups: true
